### ISSUE TITLE
JSONField not deserialized when used from inside a polymorphic inherited model

### ISSUE THREAD

**Issue by Karmak23** [rpkilby/jsonfield#101]
Hi,

I have models like this:

```
class BaseFeed(PolymorphicModel):
    errors = JSONField(default=list, blank=True)


class RssAtomFeed(BaseFeed):
    pass
```

Note: [polymorphic is here](https://github.com/chrisglass/django_polymorphic).
Say I do:

```
f1 = BaseFeed.objects.create()
f2 = RssAtomFeed.objects.create()
```

Then I got:

```
f1.errors
[]

f2.errors
u'[]'
```

And this is pretty annoying because it will obviously fail in many places because all my code expects a list.

I have read #92, but I didn't find any obvious/easy clue on how to solve this issue.

Any other hint I can try?

For the record, my models are much complex than this. You can view the [base feed here](https://github.com/1flow/1flow/blob/develop/oneflow/core/models/reldb/feed/base.py#L153) and the [rss/atom feed here](https://github.com/1flow/1flow/blob/develop/oneflow/core/models/reldb/feed/rssatom.py#L308). I've tried with or without default, with or without `load_kwargs={'object_pairs_hook': collections.OrderedDict}`, this doesn't change anything.

I've tried [the other JSONField implementation](https://github.com/derek-schaefer/django-json-field) and the problem doesn't occur, even after a south migration (I'm on Django 1.6).

regards,

**Comment by nicolaslevy** [comment]
Thanks @vietord for that fix!

**Comment by vietord** [comment]
@nicolaslevy All credit to @electroniceagle for the fix!

We have been running it in production for a while now, and we haven't run into any unexpected complications with it. (Django 1.4 environment)

However! We have not yet found ourselves in the scenario described by https://github.com/bradjasper/django-jsonfield/issues/52

None of the south(0.7.6) migrations we've done in areas which use JSONField since applying this fix do anything but simple db column addition or deletion manipulations.

**Comment by caffodian** [comment]
That fork fix seems to fix the inheritance case, but seems to break #33 again because it will try to parse ordinary strings if you pass them in as initial values.  Poking around but can't find much documentation on the whole pk throwing an error because _ptr_id property doesn't exist that seems to be the cause of the original bug...

**Comment by youssefm** [comment]
@bradjasper: here's a class of test cases that should work, but don't if they're added to `tests.py`:

```
class SubclassedJsonModel(JsonModel):
    pass

class SubclassedJsonModelTest(JSONFieldTest):
    json_model = SubclassedJsonModel
```

Instead, I'm seeing 11 failures, most of which involve the deserialization not happening, for example:

`AssertionError: u'"blah blah"' != 'blah blah'`

**Comment by rpkilby** [comment]
Hi all. Tests have added for Django's builtin multi-table inheritance, but not for integration with django-polymorphic. If there are still issues, please let me know. Thanks!
