### ISSUE TITLE
Release new version with support for Django 2.0

### ISSUE THREAD

**Issue by poxip** [rpkilby/jsonfield#215]
Hi, I see that support for Django 2.0 has been added (https://github.com/dmkoch/django-jsonfield/commit/1a65db25abdbb4d73a447005ac15efe26107f3ce), and it actually works well. The problem is that it's not released to PyPi yet. Could you please release a new version?

**Comment by dmsimard** [comment]
@dmkoch This would indeed be nice.

**Comment by syurchenko** [comment]
We are waiting for Django 2.0 support =)

**Comment by lfyzjck** [comment]
It seems that `django-jsonfield` has renamed to `jsonfield` and already release newest version.

https://pypi.org/project/jsonfield/#description

I think we can close this issue.

**Comment by rpkilby** [comment]
@lfyzjck - [`django-jsonfield`](https://bitbucket.org/schinckel/django-jsonfield) is actually a different project. It's a common source of confusion, since both repos have the same name, but different package names on PyPI. 

----

For anyone interested, I've created an updated fork called [`jsonfield2`](https://github.com/rpkilby/jsonfield2). There are a few changes, notably that it's py3k-only, Django 1.11+, and field serialization is no longer based on old South hooks.

**Comment by rpkilby** [comment]
Hi everyone. I've been granted ownership of `jsonfield` and will be maintaining it from now on. Version 3.0.0 has just been released to PyPI, which support Django 2.2 and 3.0

If you need help migrating from an older version of Django please let me know, but one of the intermediary versions of `jsonfield2` should allow you to incrementally upgrade Django.
