### ISSUE TITLE
Django Serialization + Deserialisation results in invalid data

### ISSUE THREAD

**Issue by AnnaDamm** [rpkilby/jsonfield#216]
**Description**
1. Have a model with the json field
2. Add an instance to the database with a json object inside the json field, like ``{"foo": "bar"}``
3. serialize using django's serializer:

    from django.core import serializers
        data = serializers.serialize("python", SomeModel.objects.all())

4. deserialize again
    
    serializers.deserialize("python", data)

**Behaviour**
The deserialized model has the data encoded as a string, not an actual dict, like ``"{\"foo\": \"bar\"}"``

**Expected Behaviour**
The data in the field is actually a dict

**Comment by agfunder** [comment]
I had exactly this problem.

This fixed it:

pip uninstall django-jsonfield
pip install jsonfield

(I still had to repair my stringified json field data).

**Comment by Shtirliz40k** [comment]
I have a same issue. This happens when model has no primary key. It can be reproduced this way:
`obj = Model(some_json_field='{"foo":"bar"}')`
`obj.some_json_field`

An output will be (string, not dict):
> '{"foo":"bar"}'

But if model instance has a primary key - field will contain a dict:
`obj = Model(id=123, some_json_field='{"foo":"bar"}')`
`obj.some_json_field`

>{'foo': 'bar'}


I tried to make a fixtures for a model, which contains a JSONField. So, if i provide a pk for model  - everything is fine. But when I try to use natural keys in fixture - manage.py loaddata writes a broken json string into a database, like "{\"foo\":\"bar\"}" (include double-quotes).

**Comment by rpkilby** [comment]
Hi all. I've added tests that ensure instances (saved or unsaved) can be serialized then deserialized.
